### PR TITLE
Add fedora-32 nodesets

### PR DESCRIPTION
**Pull request by ssbarnea**
@pabelanger ^

### CODE REVIEW

**Comment by pabelanger** [comment]
This is missing fedora-32 in diskimages section. That is how we build the images.

**Comment by goneri** [comment]
Could you merge the two fedora-32 PR? https://github.com/ansible-network/windmill-config/pull/680

**Comment by goneri** [comment]
@ssbarnea, you also need to defined fedora-32 labels in the pools.

**Comment by goneri** [comment]
Superseded by: https://github.com/ansible-network/windmill-config/pull/708

**Pull request closed without merging**
