### PR TITLE
aws: move centos-8-1vcpu-aws in centos-8-1vcpu pool

### PR DESCRIPTION
**Pull request by goneri**
Move the centos-8 instances in the centos-8-1vcpu.

### CODE REVIEW

**Comment by pabelanger** [comment]
@goneri do we have an idea of which jobs will be affected?

**Comment by goneri** [comment]
All the single node jobs, so the unit-tests, ansible-galaxy-importer, build-ansible-collection, VMware's govcsim jobs, and probably some more.

**Comment by pabelanger** [comment]
@goneri have we tested each job, to confirm there won't be a breakage?

**Comment by goneri** [comment]
This was the purpose of https://github.com/ansible/ansible-zuul-jobs/pull/545, I've run successfully the following jobs:

- ansible-test-cloud-integration-govcsim-python36_1_of_3
- ansible-test-cloud-integration-govcsim-python36_2_of_3
- ansible-test-cloud-integration-govcsim-python36_3_of_3
- ansible-tox-linters
- build-ansible-collection
- ansible-galaxy-importer

**Comment by pabelanger** [comment]
I don't see build-ansible-collection and ansible-galaxy-importer running on aws, still openstack driver.

**Comment by goneri** [comment]
You can follow this one: https://dashboard.zuul.ansible.com/t/ansible/status/change/40,21ae0c218342d7283f32586639e74ffaa1b9f68a

**Comment by goneri** [comment]
And indeed, `build-ansible-collection` uses indeed a different nodeset.

**Pull request merged**
